# NumPy

In [3]:
import numpy as np

In [17]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Getting Dimensions
a.ndim

1

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [19]:
# Getting Type
a.dtype

dtype('int32')

In [20]:
# Getting Size
a.itemsize

4

In [23]:
# Getting Total Size
a.size * a.itemsize

12

In [24]:
# Getting Total Size
a.nbytes

12