## Accessing/Changing specific elements, row, columns etc

In [2]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
# Get a specific element
print(a[1,-3],a[1,5])

12 13


In [9]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# Get a specific column
a[:,0]

array([1, 8])

#### [startindex:endindex:stepsize]

In [14]:
a[0, 1:6:2]

array([2, 4, 6])

In [16]:
a[0,1:-1:2]

array([2, 4, 6])

In [22]:
# Changing Value
a[1,5] = 20
print(a)

a[1,:] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 5  5  5  5  5 20  5]]
[[1 2 5 4 5 6 7]
 [5 5 5 5 5 5 5]]


### 3D Example

In [24]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# Getting specific element
b[0,1,1]

4

In [28]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [30]:
# Replacing
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
